[project]
name = "hireme-pyscript"
version = "0.1.0"
description = "Pouya's hireme website"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "gunicorn>=23.0.0",
]
