INITIAL_STATE = {
    "questions": ()
}

QUESTION_CATEGORY_ELIGIBILITY = "eligibility"
QUESTION_CATEGORY_APPLICATION = "application"
QUESTION_CATEGORIES = (
    QUESTION_CATEGORY_ELIGIBILITY, 
    QUESTION_CATEGORY_APPLICATION
)
